; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28316.0 

	TITLE	c:\K-State\cis450\runs\2020S\Assignment1\Assignment2_OriginalPrograms\question1.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_s1
_DATA	SEGMENT
COMM	_ui:DWORD
_DATA	ENDS
_DATA	SEGMENT
_s1	DW	0cH
_DATA	ENDS
PUBLIC	_main
_BSS	SEGMENT
_u2	DW	01H DUP (?)
_BSS	ENDS
_DATA	SEGMENT
_i	DD	018H
_DATA	ENDS
; Function compile flags: /Odtp
; File c:\K-State\cis450\runs\2020S\Assignment1\Assignment2_OriginalPrograms\question1.c
_TEXT	SEGMENT
_y$ = -12						; size = 4
_x$ = -8						; size = 4
_c$ = -1						; size = 1
_argc$ = 8						; size = 4
_argv$ = 12						; size = 4
_envp$ = 16						; size = 4
_main	PROC
  00000	55		 push	 ebp
  00001	8b ec		 mov	 ebp, esp
  00003	83 ec 0c	 sub	 esp, 12			; 0000000cH
  00006	0f bf 05 00 00
	00 00		 movsx	 eax, WORD PTR _s1
  0000d	6b 0d 00 00 00
	00 03		 imul	 ecx, DWORD PTR _i, 3   ; ecx <= i * 3
  00014	03 c1		 add	 eax, ecx
  00016	89 45 f8	 mov	 DWORD PTR _x$[ebp], eax
  00019	8b 55 f8	 mov	 edx, DWORD PTR _x$[ebp]
  0001c	83 c2 06	 add	 edx, 6
  0001f	66 89 15 00 00
	00 00		 mov	 WORD PTR _u2, dx
  00026	0f bf 05 00 00
	00 00		 movsx	 eax, WORD PTR _s1
  0002d	83 c0 0f	 add	 eax, 15			; 0000000fH
  00030	a3 00 00 00 00	 mov	 DWORD PTR _ui, eax
  00035	c6 45 ff 05	 mov	 BYTE PTR _c$[ebp], 5
  00039	c7 45 f4 00 00
	00 00		 mov	 DWORD PTR _y$[ebp], 0
$LN4@main:
  00040	8b 4d f4	 mov	 ecx, DWORD PTR _y$[ebp]
  00043	83 c1 01	 add	 ecx, 1
  00046	89 4d f4	 mov	 DWORD PTR _y$[ebp], ecx
  00049	0f b7 15 00 00
	00 00		 movzx	 edx, WORD PTR _u2
  00050	8b 45 f8	 mov	 eax, DWORD PTR _x$[ebp]
  00053	2b c2		 sub	 eax, edx
  00055	0f be 4d ff	 movsx	 ecx, BYTE PTR _c$[ebp]
  00059	2b c1		 sub	 eax, ecx
  0005b	89 45 f8	 mov	 DWORD PTR _x$[ebp], eax
  0005e	83 7d f8 00	 cmp	 DWORD PTR _x$[ebp], 0
  00062	7f dc		 jg	 SHORT $LN4@main
  00064	8b 15 00 00 00
	00		 mov	 edx, DWORD PTR _i
  0006a	d1 e2		 shl	 edx, 1
  0006c	39 55 f8	 cmp	 DWORD PTR _x$[ebp], edx
  0006f	7d 17		 jge	 SHORT $LN5@main
  00071	0f be 45 ff	 movsx	 eax, BYTE PTR _c$[ebp]
  00075	0f b7 0d 00 00
	00 00		 movzx	 ecx, WORD PTR _u2
  0007c	8d 54 88 2d	 lea	 edx, DWORD PTR [eax+ecx*4+45]
  00080	89 15 00 00 00
	00		 mov	 DWORD PTR _ui, edx
  00086	eb 13		 jmp	 SHORT $LN1@main
$LN5@main:
  00088	8b 45 f8	 mov	 eax, DWORD PTR _x$[ebp]
  0008b	03 45 f4	 add	 eax, DWORD PTR _y$[ebp]
  0008e	0f be 4d ff	 movsx	 ecx, BYTE PTR _c$[ebp]
  00092	d1 e1		 shl	 ecx, 1
  00094	2b c1		 sub	 eax, ecx
  00096	a3 00 00 00 00	 mov	 DWORD PTR _i, eax
$LN1@main:
  0009b	33 c0		 xor	 eax, eax
  0009d	8b e5		 mov	 esp, ebp
  0009f	5d		 pop	 ebp
  000a0	c3		 ret	 0
_main	ENDP
_TEXT	ENDS
END
